#!/bin/bash

DOT="$HOME/dotfiles/configs"

for item in "$DOT"/*; do
    [ -e "$item" ] || continue

    name=$(basename "$item")

    target=$(readlink "$HOME/.config/$name" 2>/dev/null)

    if [ "$target" = "$item" ]; then
        echo "OKAY: $name"
    else
        echo "BROKEN: $name"
    fi
done
